@url = http://127.0.0.1:5000

### 1. Cadastrar um Livro
POST {{url}}/livros
Content-Type: application/json

{
  "titulo": "Clean Code",
  "autor": "Robert Martin",
  "isbn": "123456"
}

### 2. Listar Livros (Para mostrar que salvou)
GET {{url}}/livros

### 3. Cadastrar um Usuário
POST {{url}}/usuarios
Content-Type: application/json

{
  "nome": "João",
  "id_usuario": "001"
}

### 4. Realizar Empréstimo
POST {{url}}/emprestimos
Content-Type: application/json

{
  "isbn": "123456",
  "id_usuario": "001"
}

### 5. Tentar Emprestar de novo (Para mostrar o erro 400 - Livro Indisponível)
POST {{url}}/emprestimos
Content-Type: application/json

{
  "isbn": "123456",
  "id_usuario": "001"
}

### 6. Devolver Livro
POST {{url}}/devolver
Content-Type: application/json

{
  "isbn": "123456",
  "id_usuario": "001"
}

### 7. Listar Livros Após Devolução
GET {{url}}/livros